export const WORKSPACE = {
  SET_PLAYING: "SET_PLAYING",
  SET_METRONOME_SOUND: "SET_METRONOME_SOUND",
  SET_BPM: "SET_BPM",
  SET_BEATS_PER_BAR: "SET_BEATS_PER_BAR"
};

export const USER = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER"
};
