export const WORKSPACE = {
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  STOP: "STOP",
  SET_METRONOME_SOUND: "SET_METRONOME_SOUND",
  SET_BPM: "SET_BPM",
  SET_BEATS_PER_BAR: "SET_BEATS_PER_BAR",
  SET_PLAY_POSITION: "SET_PLAY_POSITION"
};

export const USER = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER"
};
